"""changed structure of community table

Revision ID: 0cd48a4d6e4b
Revises: 0eb4040f7c6b
Create Date: 2023-11-23 23:18:59.014865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd48a4d6e4b'
down_revision: Union[str, None] = '0eb4040f7c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
