"""migration to new data structure

Revision ID: 0eb4040f7c6b
Revises: 655156fb69bf
Create Date: 2023-11-23 22:47:09.465984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0eb4040f7c6b'
down_revision: Union[str, None] = '655156fb69bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('current_page', 'community')
    op.create_table('phash_history',
    sa.Column('phash_history_id', mysql.INTEGER(), nullable=False),
    sa.Column('community_id', mysql.INTEGER(), nullable=True),
    sa.Column('phash', mysql.VARCHAR(length=16), nullable=True),
    sa.PrimaryKeyConstraint('phash_history_id')
    )
    op.create_table('user',
    sa.Column('actor_id', mysql.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('actor_id')
    )
    op.create_table('content',
    sa.Column('content_id', mysql.INTEGER(), nullable=False),
    sa.Column('actor_id', mysql.VARCHAR(), nullable=True),
    sa.Column('community_id', mysql.INTEGER(), nullable=True),
    sa.Column('parent_content_id', mysql.INTEGER(), nullable=True),
    sa.Column('root_content_id', mysql.INTEGER(), nullable=True),
    sa.Column('content_type', sa.Enum('REMOVED', 'DISMISSED', name='outcome'), nullable=True),
    sa.Column('lemmy_content_id', mysql.INTEGER(), nullable=True),
    sa.Column('should_rescan', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user.actor_id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['community.community_id'], ),
    sa.ForeignKeyConstraint(['parent_content_id'], ['content.content_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('post_phash_history',
    sa.Column('post_id', mysql.INTEGER(), nullable=False),
    sa.Column('phash_history_id', mysql.INTEGER(), nullable=True),
    sa.Column('community_id', mysql.INTEGER(), nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.Column('phash', mysql.VARCHAR(length=16), nullable=True),
    sa.ForeignKeyConstraint(['phash_history_id'], ['phash_history.phash_history_id'], ),
    sa.PrimaryKeyConstraint('post_id', 'community_id')
    )
    op.create_table('user_community_statistics',
    sa.Column('statistics_id', mysql.INTEGER(), nullable=False),
    sa.Column('actor_id', mysql.VARCHAR(), nullable=True),
    sa.Column('community_id', mysql.INTEGER(), nullable=True),
    sa.Column('report_count', mysql.INTEGER(), nullable=True),
    sa.Column('warned_count', mysql.INTEGER(), nullable=True),
    sa.Column('removed_count', mysql.INTEGER(), nullable=True),
    sa.Column('ban_count', mysql.INTEGER(), nullable=True),
    sa.Column('banned_until', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user.actor_id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['community.community_id'], ),
    sa.PrimaryKeyConstraint('statistics_id')
    )
    op.create_table('content_field',
    sa.Column('content_field_id', mysql.INTEGER(), nullable=False),
    sa.Column('content_id', mysql.INTEGER(), nullable=True),
    sa.Column('content_field_type', sa.Enum('COMMENT_CONTENT', 'POST_CONTENT', 'POST_TITLE', 'POST_URL', name='contentfieldtype'), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.PrimaryKeyConstraint('content_field_id')
    )
    op.create_table('report',
    sa.Column('report_id', mysql.INTEGER(), nullable=False),
    sa.Column('actor_id', mysql.VARCHAR(), nullable=True),
    sa.Column('content_id', mysql.INTEGER(), nullable=True),
    sa.Column('reason', mysql.TEXT(), nullable=True),
    sa.Column('outcome', sa.Enum('REMOVED', 'DISMISSED', name='outcome'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user.actor_id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('content_field_history',
    sa.Column('content_field_history_id', mysql.INTEGER(), nullable=False),
    sa.Column('content_field_id', mysql.INTEGER(), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('timestamp', mysql.TIMESTAMP(), nullable=True),
    sa.Column('scan_timestamp', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['content_field_id'], ['content_field.content_field_id'], ),
    sa.PrimaryKeyConstraint('content_field_history_id')
    )
    op.create_table('content_metadata',
    sa.Column('content_metadata_id', mysql.INTEGER(), nullable=False),
    sa.Column('content_field_history_id', mysql.INTEGER(), nullable=True),
    sa.Column('content_id', mysql.INTEGER(), nullable=True),
    sa.Column('key', mysql.TEXT(), nullable=True),
    sa.Column('value', mysql.TEXT(), nullable=True),
    sa.Column('current', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['content_field_history_id'], ['content_field_history.content_field_history_id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.PrimaryKeyConstraint('content_metadata_id')
    )
    op.create_table('content_result',
    sa.Column('content_result_id', mysql.INTEGER(), nullable=False),
    sa.Column('content_field_history_id', mysql.INTEGER(), nullable=True),
    sa.Column('content_id', mysql.INTEGER(), nullable=True),
    sa.Column('processor', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('tags', mysql.TEXT(), nullable=True),
    sa.Column('current', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['content_field_history_id'], ['content_field_history.content_field_history_id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ),
    sa.PrimaryKeyConstraint('content_result_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('community', 'current_page')
    op.drop_table('content_result')
    op.drop_table('content_metadata')
    op.drop_table('content_field_history')
    op.drop_table('report')
    op.drop_table('content_field')
    op.drop_table('user_community_statistics')
    op.drop_table('post_phash_history')
    op.drop_table('content')
    op.drop_table('user')
    op.drop_table('phash_history')
    # ### end Alembic commands ###
