"""removed redundant phash table

Revision ID: 5d94816322de
Revises: 0cd48a4d6e4b
Create Date: 2023-11-24 21:47:45.409687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d94816322de'
down_revision: Union[str, None] = '0cd48a4d6e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_phash_history', schema=None) as batch_op:
        batch_op.drop_column('phash_history_id')
    op.drop_table('phash_history')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_phash_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phash_history_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'phash_history', ['phash_history_id'], ['phash_history_id'])

    op.create_table('phash_history',
    sa.Column('phash_history_id', sa.INTEGER(), nullable=False),
    sa.Column('community_id', sa.INTEGER(), nullable=True),
    sa.Column('phash', sa.VARCHAR(length=16), nullable=True),
    sa.PrimaryKeyConstraint('phash_history_id')
    )
    # ### end Alembic commands ###
