"""initial database structure

Revision ID: 655156fb69bf
Revises: 20406b4c2dae
Create Date: 2023-11-23 22:38:34.685733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '655156fb69bf'
down_revision: Union[str, None] = '20406b4c2dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_page',
    sa.Column('community_name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('post_page', mysql.INTEGER(), nullable=True),
    sa.Column('comment_page', mysql.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('community_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current_page')
    # ### end Alembic commands ###
